### ISSUE TITLE
unpack error

### ISSUE THREAD

**Issue by homopolymer** [chengyuan/reago#1]
Hi

I try to run reago on paired-end data, and failed at the second step.  The error messages are as follows.  How to run reago correctly?

Traceback (most recent call last):
  File "/home/fzeng/Tool/MetagenomeTools/reago/reago.py", line 955, in <module>
    scaf, remaining  = scaffold(scaffold_candidate)
  File "/home/fzeng/Tool/MetagenomeTools/reago/reago.py", line 713, in scaffold
    conf[i][j] = max(conf_connect(path_1, path_2), conf_connect(path_2, path_1))
  File "/home/fzeng/Tool/MetagenomeTools/reago/reago.py", line 683, in conf_connect
    base, sp, end = read_id.split(".")
ValueError: need more than 2 values to unpack

**Comment by chengyuan** [comment]
Could you send me a sample of your input file please, so I can look into the problem?

Thanks!

Cheng

**Comment by chengyuan** [comment]
Btw ,REAGO assumes the sequence names of a read pair to be
XXXX.1 &
XXXX.2
The only difference of their names is the last character.

Let me know the same error occurs if your input file does follow the above
format.

Thanks,
Cheng

Sent from my iPhone

On Aug 13, 2015, at 6:56 AM, Feng Zeng notifications@github.com wrote:

Hi

I try to run reago on paired-end data, and failed at the second step. The
error messages are as follows. How to run reago correctly?

Traceback (most recent call last):
File "/home/fzeng/Tool/MetagenomeTools/reago/reago.py", line 955, in
scaf, remaining = scaffold(scaffold_candidate)
File "/home/fzeng/Tool/MetagenomeTools/reago/reago.py", line 713, in
scaffold
conf[i][j] = max(conf_connect(path_1, path_2), conf_connect(path_2, path_1))
File "/home/fzeng/Tool/MetagenomeTools/reago/reago.py", line 683, in
conf_connect
base, sp, end = read_id.split(".")
ValueError: need more than 2 values to unpack

—
Reply to this email directly or view it on GitHub
https://github.com/chengyuan/reago/issues/1.

**Comment by homopolymer** [comment]
Hi Cheng Yuan

Thanks for the reply.  The data is too huge to attach and send.  I am using a CAMI toy data (225 genomes), and could be downloaded here http://cami-challenge.org/ http://cami-challenge.org/.

Here is a clip of the data including pair 1 and pair 2:
[1] Pair 1

> M2|S2|R0.1
> TGAAACCGCCGAGGCCGCCACCCGCGCCTATGTGCTGCACCCCGACCTGAGGGCCGACCGCGAGCGGCGTCTGGCCGAGAACGGGCTGGCCGAGGCGGTG
> M2|S2|R1.1
> GTTACGACAGTTGGGCTTATGTGGAAGGAACTGTGCGTCAGGAAAAAACATCTACGTTGTACCCCGGATCCAACACATTCGTTTATCCTTCTGTGAACGG
> M2|S2|R2.1
> CCTACCGGCTCTACTTCAACGGCGCCGTGGCGGACTCCCGCGGTGGTGGCCAGATCACCCTCGGCGGGCCGTCGCCGGCGGCCAGCCCCTTCCTACTGGA
> M2|S2|R3.1
> CCGTATGCCCTTGCCAATGATGCCCGCTCCTTCGTCACTCGTATGCAGAAGGTGCTGCCTCCCGAAAATAGGTTGGTCATGTCTTACAATAACAAAATTG
> M2|S2|R4.1
> CTGCGGTTGAACACCTTCAGGTCTGGGGTCAGCGCAACAATATTCCGGTGATTGCCCAGCATACCGGTGCGGATTCCGCCTCTGTTATCTTCGACGCCAT

[2] Pair 2

> M2|S2|R0.2
> ACCGCGCCTTCATCTCATCGACCTTGCCCGAGCCGAACAGCGTGCCGGGCTGCATCCGCCCGACGCGCACCACTTCGGAACCCACAACCTCCAGATTGGG
> M2|S2|R1.2
> TAATCCAGCCATTCGGGTTTATTATCTTTCAGCAAAGATGAATAAATGACGCTACCGTTCACAGAAGGATAAACGAATGTGTCGGATCCGGGGTACAACG
> M2|S2|R2.2
> TGCGAGTAGAGATAAGACAGCGCCGGATGGCGGTTGAAGAAACGCACCAGACGCGGCAGCAGCCGTGGCTCCAGTAGGAAGGGGCTGGCCGCCCGCGACG
> M2|S2|R3.2
> CCAATCATCAACCATTTTTTTCACTAAATCGATCCATTTGGACTGGTCATGTTCATTGCTAGTCGTAGAGAACAGGACATTTTTGTTATTGTAAGACATG
> M2|S2|R4.2
> TTTTCTTCAACTCTTCCATCAGATGCGATTTGTTCTGCAGACGTCCGGCGGTATCGGCAATCAGGACGTCGATATTACGCGCTTTAGCTGCCTGAATGGC

Best Regards

Feng Zeng, Ph.D
Department of Automation
Xiamen University

**Comment by homopolymer** [comment]
Btw, it works for the example data provided in the github server.

Best Regards

Feng Zeng, Ph.D
Department of Automation
Xiamen University

**Comment by chengyuan** [comment]
Is there any output in the filtered.fasta after the 1st stage? If so, could
you send me the file please?

Thanks,
Cheng

**Comment by homopolymer** [comment]
Could you give me other mail address? GitHub mail server could not receive attachment.

Best Regards

Feng Zeng, Ph.D
Department of Automation
Xiamen University

**Comment by chengyuan** [comment]
chengy@msu.edu
