### ISSUE TITLE
Illegal comparison in remove_junk_node function?

### ISSUE THREAD

**Issue by pjeraldo** [chengyuan/reago#2]
Hello,

I noticed an illegal comparison inside the remove_junk_node function, were the code compares the _string_ `read_dict[node]` to the _float_ `READ_LEN * 1.05`:

``` python
if  not G.in_degree(node) and not G.out_degree(node) and \
            (n_read_in_node(node) < 5 or read_dict[node] < READ_LEN * 1.05):
```

Link to line in the repo:
https://github.com/chengyuan/reago/blob/7925915feb341a82ca7a99e3ed867614e27a3627/reago.py#L535 

The error is _silent_ in python 2.7.3, apparently, but python 3.4.3 throws an error there.

If I make the assumption than you were comparing the length of the sequence `len(read_dict[node])` to `READ_LEN * 1.05`, the code works again, _but the results change_: the number and length of the reported assembled genes changes somewhat.

 Please take a look at this issue. This is a useful piece of software, and it's unfortunate that python sometimes silently lets issues like this go through.

Thanks, and best regards,

Patricio Jeraldo

**Comment by chengyuan** [comment]
Patricio,

Thanks for pointing it out! I'm putting together a new version of reago. I will address the problem in it.

Cheng

**Comment by chengyuan** [comment]
REAGO v1.1 has been released, I fixed a few bugs, including the one you found. 
Check this out. https://github.com/chengyuan/reago-1.1
Thanks!

Cheng

**Comment by pjeraldo** [comment]
Thank you for your prompt response. Much appreciated.

Patricio
